
var c;c||(c=typeof SilkSDK !== 'undefined' ? SilkSDK : {});c.locateFile=function(a,b){return b+"../"+a};var h={},n;for(n in c)c.hasOwnProperty(n)&&(h[n]=c[n]);var aa=[],ba="./this.program";function q(a,b){throw b;}var t="",v,ca;t=self.location.href;t=0!==t.indexOf("blob:")?t.substr(0,t.lastIndexOf("/")+1):"";v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
ca=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var x=c.print||console.log.bind(console),y=c.printErr||console.warn.bind(console);for(n in h)h.hasOwnProperty(n)&&(c[n]=h[n]);h=null;c.arguments&&(aa=c.arguments);c.thisProgram&&(ba=c.thisProgram);c.quit&&(q=c.quit);var C;c.wasmBinary&&(C=c.wasmBinary);var noExitRuntime;c.noExitRuntime&&(noExitRuntime=c.noExitRuntime);"object"!==typeof WebAssembly&&E("no native wasm support detected");
var da,ea=!1,fa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&fa)return fa.decode(a.subarray(b,d));for(e="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}
function G(a,b,d,e){if(!(0<e))return 0;var f=d;e=d+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(d>=e)break;b[d++]=k}else{if(2047>=k){if(d+1>=e)break;b[d++]=192|k>>6}else{if(65535>=k){if(d+2>=e)break;b[d++]=224|k>>12}else{if(d+3>=e)break;b[d++]=240|k>>18;b[d++]=128|k>>12&63}b[d++]=128|k>>6&63}b[d++]=128|k&63}}b[d]=0;return d-f}
function H(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function ha(a){var b=H(a)+1,d=ia(b);G(a,I,d,b);return d}var ja,I,J,ka,K;
function la(){var a=da.buffer;ja=a;c.HEAP8=I=new Int8Array(a);c.HEAP16=ka=new Int16Array(a);c.HEAP32=K=new Int32Array(a);c.HEAPU8=J=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAPU32=new Uint32Array(a);c.HEAPF32=new Float32Array(a);c.HEAPF64=new Float64Array(a)}var ma,na=[],oa=[],pa=[],qa=[],ra=!1;oa.push({fc:function(){sa()}});function ta(){var a=c.preRun.shift();na.unshift(a)}var L=0,ua=null,M=null;function va(){L++;c.monitorRunDependencies&&c.monitorRunDependencies(L)}
function wa(){L--;c.monitorRunDependencies&&c.monitorRunDependencies(L);if(0==L&&(null!==ua&&(clearInterval(ua),ua=null),M)){var a=M;M=null;a()}}c.preloadedImages={};c.preloadedAudios={};function E(a){if(c.onAbort)c.onAbort(a);y(a);ea=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function xa(){var a=N;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
var N="silksdk.wasm";if(!xa()){var ya=N;N=c.locateFile?c.locateFile(ya,t):t+ya}function za(){var a=N;try{if(a==N&&C)return new Uint8Array(C);if(ca)return ca(a);throw"both async and sync fetching of the wasm failed";}catch(b){E(b)}}function Aa(){return C||"function"!==typeof fetch?Promise.resolve().then(function(){return za()}):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return za()})}
var P,Q;function R(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(c);else{var d=b.fc;"number"===typeof d?void 0===b.Ka?ma.get(d)():ma.get(d)(b.Ka):d(void 0===b.Ka?null:b.Ka)}}}c.callRuntimeCallbacks=R;c.demangle=function(a){return a};function Ba(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}c.demangleAll=Ba;
function Ca(){var a=Error();if(!a.stack){try{throw Error();}catch(b){a=b}if(!a.stack)return"(no stack trace available)"}return a.stack.toString()}c.jsStackTrace=Ca;c.stackTrace=function(){var a=Ca();c.extraStackTrace&&(a+="\n"+c.extraStackTrace());return Ba(a)};function Da(a){return K[Ea()>>2]=a}c.setErrNo=Da;
var S={Ab:function(a){return/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1)},Za:function(a,b){for(var d=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),d++):d&&(a.splice(e,1),d--)}if(b)for(;d;d--)a.unshift("..");return a},normalize:function(a){var b="/"===a.charAt(0),d="/"===a.substr(-1);(a=S.Za(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&d&&(a+="/");return(b?"/":"")+a},dirname:function(a){var b=S.Ab(a);
a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},X:function(a){if("/"===a)return"/";a=S.normalize(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Qc:function(a){return S.Ab(a)[3]},join:function(){return S.normalize(Array.prototype.slice.call(arguments,0).join("/"))},fa:function(a,b){return S.normalize(a+"/"+b)}};c.PATH=S;
function Fa(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){E("randomDevice")}}c.getRandomDevice=Fa;
var V={resolve:function(){for(var a="",b=!1,d=arguments.length-1;-1<=d&&!b;d--){b=0<=d?arguments[d]:U.Ca();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=S.Za(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."},zb:function(a,b){function d(k){for(var m=0;m<k.length&&""===k[m];m++);for(var r=k.length-1;0<=r&&""===k[r];r--);return m>r?[]:k.slice(m,r-m+1)}a=V.resolve(a).substr(1);b=V.resolve(b).substr(1);
a=d(a.split("/"));b=d(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}};c.PATH_FS=V;
var W={Db:[],da:function(){},ld:function(){},register:function(a,b){W.Db[a]={input:[],M:[],ma:b};U.cb(a,W.D)},D:{open:function(a){var b=W.Db[a.node.wa];if(!b)throw new U.A(43);a.I=b;a.seekable=!1},close:function(a){a.I.ma.flush(a.I)},flush:function(a){a.I.ma.flush(a.I)},read:function(a,b,d,e){if(!a.I||!a.I.ma.sb)throw new U.A(60);for(var f=0,g=0;g<e;g++){try{var k=a.I.ma.sb(a.I)}catch(m){throw new U.A(29);}if(void 0===k&&0===f)throw new U.A(6);if(null===k||void 0===k)break;f++;b[d+g]=k}f&&(a.node.timestamp=
Date.now());return f},write:function(a,b,d,e){if(!a.I||!a.I.ma.$a)throw new U.A(60);try{for(var f=0;f<e;f++)a.I.ma.$a(a.I,b[d+f])}catch(g){throw new U.A(29);}e&&(a.node.timestamp=Date.now());return f}},Zb:{sb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ga(b)}return a.input.shift()},$a:function(a,b){null===
b||10===b?(x(F(a.M,0)),a.M=[]):0!=b&&a.M.push(b)},flush:function(a){a.M&&0<a.M.length&&(x(F(a.M,0)),a.M=[])}},Yb:{$a:function(a,b){null===b||10===b?(y(F(a.M,0)),a.M=[]):0!=b&&a.M.push(b)},flush:function(a){a.M&&0<a.M.length&&(y(F(a.M,0)),a.M=[])}}};c.TTY=W;function Ha(a){var b=16384*Math.ceil(a/16384);for(var d=Ia(b);a<b;)I[d+a++]=0;return d}c.mmapAlloc=Ha;
var X={V:null,H:function(){return X.createNode(null,"/",16895,0)},createNode:function(a,b,d,e){if(U.kc(d)||U.lc(d))throw new U.A(63);X.V||(X.V={dir:{node:{R:X.B.R,L:X.B.L,ga:X.B.ga,T:X.B.T,ya:X.B.ya,na:X.B.na,za:X.B.za,xa:X.B.xa,ba:X.B.ba},stream:{S:X.D.S}},file:{node:{R:X.B.R,L:X.B.L},stream:{S:X.D.S,read:X.D.read,write:X.D.write,qa:X.D.qa,ta:X.D.ta,la:X.D.la}},link:{node:{R:X.B.R,L:X.B.L,aa:X.B.aa},stream:{}},ib:{node:{R:X.B.R,L:X.B.L},stream:U.Pb}});d=U.createNode(a,b,d,e);U.K(d.mode)?(d.B=X.V.dir.node,
d.D=X.V.dir.stream,d.C={}):U.isFile(d.mode)?(d.B=X.V.file.node,d.D=X.V.file.stream,d.G=0,d.C=null):U.sa(d.mode)?(d.B=X.V.link.node,d.D=X.V.link.stream):U.Da(d.mode)&&(d.B=X.V.ib.node,d.D=X.V.ib.stream);d.timestamp=Date.now();a&&(a.C[b]=d,a.timestamp=d.timestamp);return d},Wc:function(a){return a.C?a.C.subarray?a.C.subarray(0,a.G):new Uint8Array(a.C):new Uint8Array(0)},ob:function(a,b){var d=a.C?a.C.length:0;d>=b||(b=Math.max(b,d*(1048576>d?2:1.125)>>>0),0!=d&&(b=Math.max(b,256)),d=a.C,a.C=new Uint8Array(b),
0<a.G&&a.C.set(d.subarray(0,a.G),0))},xc:function(a,b){if(a.G!=b)if(0==b)a.C=null,a.G=0;else{var d=a.C;a.C=new Uint8Array(b);d&&a.C.set(d.subarray(0,Math.min(b,a.G)));a.G=b}},B:{R:function(a){var b={};b.$b=U.Da(a.mode)?a.id:1;b.Ta=a.id;b.mode=a.mode;b.tc=1;b.uid=0;b.jc=0;b.wa=a.wa;U.K(a.mode)?b.size=4096:U.isFile(a.mode)?b.size=a.G:U.sa(a.mode)?b.size=a.link.length:b.size=0;b.Lb=new Date(a.timestamp);b.qc=new Date(a.timestamp);b.Xb=new Date(a.timestamp);b.Mb=4096;b.Nb=Math.ceil(b.size/b.Mb);return b},
L:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.xc(a,b.size)},ga:function(){throw U.Oa[44];},T:function(a,b,d,e){return X.createNode(a,b,d,e)},ya:function(a,b,d){if(U.K(a.mode)){try{var e=U.W(b,d)}catch(g){}if(e)for(var f in e.C)throw new U.A(55);}delete a.parent.C[a.name];a.parent.timestamp=Date.now();a.name=d;b.C[d]=a;b.timestamp=a.parent.timestamp;a.parent=b},na:function(a,b){delete a.C[b];a.timestamp=Date.now()},za:function(a,
b){var d=U.W(a,b),e;for(e in d.C)throw new U.A(55);delete a.C[b];a.timestamp=Date.now()},xa:function(a){var b=[".",".."],d;for(d in a.C)a.C.hasOwnProperty(d)&&b.push(d);return b},ba:function(a,b,d){a=X.createNode(a,b,41471,0);a.link=d;return a},aa:function(a){if(!U.sa(a.mode))throw new U.A(28);return a.link}},D:{read:function(a,b,d,e,f){var g=a.node.C;if(f>=a.node.G)return 0;a=Math.min(a.node.G-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),d);else for(e=0;e<a;e++)b[d+e]=g[f+e];return a},write:function(a,
b,d,e,f,g){b.buffer===I.buffer&&(g=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.C||a.C.subarray)){if(g)return a.C=b.subarray(d,d+e),a.G=e;if(0===a.G&&0===f)return a.C=b.slice(d,d+e),a.G=e;if(f+e<=a.G)return a.C.set(b.subarray(d,d+e),f),e}X.ob(a,f+e);if(a.C.subarray&&b.subarray)a.C.set(b.subarray(d,d+e),f);else for(g=0;g<e;g++)a.C[f+g]=b[d+g];a.G=Math.max(a.G,f+e);return e},S:function(a,b,d){1===d?b+=a.position:2===d&&U.isFile(a.node.mode)&&(b+=a.node.G);if(0>b)throw new U.A(28);
return b},qa:function(a,b,d){X.ob(a.node,b+d);a.node.G=Math.max(a.node.G,b+d)},ta:function(a,b,d,e,f,g){if(0!==b)throw new U.A(28);if(!U.isFile(a.node.mode))throw new U.A(43);a=a.node.C;if(g&2||a.buffer!==ja){if(0<e||e+d<a.length)a.subarray?a=a.subarray(e,e+d):a=Array.prototype.slice.call(a,e,e+d);e=!0;d=Ha(d);if(!d)throw new U.A(48);I.set(a,d)}else e=!1,d=a.byteOffset;return{gd:d,Cc:e}},la:function(a,b,d,e,f){if(!U.isFile(a.node.mode))throw new U.A(43);if(f&2)return 0;X.D.write(a,b,0,e,d,!1);return 0}}};
c.MEMFS=X;
var U={root:null,va:[],mb:{},streams:[],rc:1,U:null,lb:"/",Sa:!1,wb:!0,J:{},Cb:{yb:{Hb:1,Ib:2}},A:null,Oa:{},dc:null,Ha:0,F:function(a,b){a=V.resolve(U.Ca(),a);b=b||{};if(!a)return{path:"",node:null};var d={Na:!0,bb:0},e;for(e in d)void 0===b[e]&&(b[e]=d[e]);if(8<b.bb)throw new U.A(32);a=S.Za(a.split("/").filter(function(k){return!!k}),!1);var f=U.root;d="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=U.W(f,a[e]);d=S.fa(d,a[e]);U.ea(f)&&(!g||g&&b.Na)&&(f=f.ua.root);if(!g||
b.O)for(g=0;U.sa(f.mode);)if(f=U.aa(d),d=V.resolve(S.dirname(d),f),f=U.F(d,{bb:b.bb}).node,40<g++)throw new U.A(32);}return{path:d,node:f}},Z:function(a){for(var b;;){if(U.Ea(a))return a=a.H.xb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ra:function(a,b){for(var d=0,e=0;e<b.length;e++)d=(d<<5)-d+b.charCodeAt(e)|0;return(a+d>>>0)%U.U.length},ub:function(a){var b=U.Ra(a.parent.id,a.name);a.ia=U.U[b];U.U[b]=a},vb:function(a){var b=U.Ra(a.parent.id,a.name);if(U.U[b]===a)U.U[b]=
a.ia;else for(b=U.U[b];b;){if(b.ia===a){b.ia=a.ia;break}b=b.ia}},W:function(a,b){var d=U.nc(a);if(d)throw new U.A(d,a);for(d=U.U[U.Ra(a.id,b)];d;d=d.ia){var e=d.name;if(d.parent.id===a.id&&e===b)return d}return U.ga(a,b)},createNode:function(a,b,d,e){a=new U.Fb(a,b,d,e);U.ub(a);return a},La:function(a){U.vb(a)},Ea:function(a){return a===a.parent},ea:function(a){return!!a.ua},isFile:function(a){return 32768===(a&61440)},K:function(a){return 16384===(a&61440)},sa:function(a){return 40960===(a&61440)},
Da:function(a){return 8192===(a&61440)},kc:function(a){return 24576===(a&61440)},lc:function(a){return 4096===(a&61440)},Xc:function(a){return 49152===(a&49152)},ec:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},pc:function(a){var b=U.ec[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},pb:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},$:function(a,b){if(U.wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&
!(a.mode&73))return 2}else return 2;return 0},nc:function(a){var b=U.$(a,"x");return b?b:a.B.ga?0:2},Ya:function(a,b){try{return U.W(a,b),20}catch(d){}return U.$(a,"wx")},Fa:function(a,b,d){try{var e=U.W(a,b)}catch(f){return f.P}if(a=U.$(a,"wx"))return a;if(d){if(!U.K(e.mode))return 54;if(U.Ea(e)||U.Z(e)===U.Ca())return 10}else if(U.K(e.mode))return 31;return 0},oc:function(a,b){return a?U.sa(a.mode)?32:U.K(a.mode)&&("r"!==U.pb(b)||b&512)?31:U.$(a,U.pb(b)):44},Gb:4096,sc:function(a,b){b=b||U.Gb;for(a=
a||0;a<=b;a++)if(!U.streams[a])return a;throw new U.A(33);},ca:function(a){return U.streams[a]},Wb:function(a,b,d){U.Ia||(U.Ia=function(){},U.Ia.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var e=new U.Ia,f;for(f in a)e[f]=a[f];a=e;b=U.sc(b,d);a.ja=b;return U.streams[b]=a},Qb:function(a){U.streams[a]=null},Pb:{open:function(a){a.D=U.hc(a.node.wa).D;a.D.open&&a.D.open(a)},S:function(){throw new U.A(70);}},Xa:function(a){return a>>8},cd:function(a){return a&255},
ha:function(a,b){return a<<8|b},cb:function(a,b){U.mb[a]={D:b}},hc:function(a){return U.mb[a]},rb:function(a){var b=[];for(a=[a];a.length;){var d=a.pop();b.push(d);a.push.apply(a,d.va)}return b},Bb:function(a,b){function d(k){U.Ha--;return b(k)}function e(k){if(k){if(!e.cc)return e.cc=!0,d(k)}else++g>=f.length&&d(null)}"function"===typeof a&&(b=a,a=!1);U.Ha++;1<U.Ha&&y("warning: "+U.Ha+" FS.syncfs operations in flight at once, probably just doing extra work");var f=U.rb(U.root.H),g=0;f.forEach(function(k){if(!k.type.Bb)return e(null);
k.type.Bb(k,a,e)})},H:function(a,b,d){var e="/"===d,f=!d;if(e&&U.root)throw new U.A(10);if(!e&&!f){var g=U.F(d,{Na:!1});d=g.path;g=g.node;if(U.ea(g))throw new U.A(10);if(!U.K(g.mode))throw new U.A(54);}b={type:a,fd:b,xb:d,va:[]};a=a.H(b);a.H=b;b.root=a;e?U.root=a:g&&(g.ua=b,g.H&&g.H.va.push(b));return a},nd:function(a){a=U.F(a,{Na:!1});if(!U.ea(a.node))throw new U.A(28);a=a.node;var b=a.ua,d=U.rb(b);Object.keys(U.U).forEach(function(e){for(e=U.U[e];e;){var f=e.ia;-1!==d.indexOf(e.H)&&U.La(e);e=f}});
a.ua=null;a.H.va.splice(a.H.va.indexOf(b),1)},ga:function(a,b){return a.B.ga(a,b)},T:function(a,b,d){var e=U.F(a,{parent:!0}).node;a=S.X(a);if(!a||"."===a||".."===a)throw new U.A(28);var f=U.Ya(e,a);if(f)throw new U.A(f);if(!e.B.T)throw new U.A(63);return e.B.T(e,a,b,d)},create:function(a,b){return U.T(a,(void 0!==b?b:438)&4095|32768,0)},N:function(a,b){return U.T(a,(void 0!==b?b:511)&1023|16384,0)},dd:function(a,b){a=a.split("/");for(var d="",e=0;e<a.length;++e)if(a[e]){d+="/"+a[e];try{U.N(d,b)}catch(f){if(20!=
f.P)throw f;}}},Ga:function(a,b,d){"undefined"===typeof d&&(d=b,b=438);return U.T(a,b|8192,d)},ba:function(a,b){if(!V.resolve(a))throw new U.A(44);var d=U.F(b,{parent:!0}).node;if(!d)throw new U.A(44);b=S.X(b);var e=U.Ya(d,b);if(e)throw new U.A(e);if(!d.B.ba)throw new U.A(63);return d.B.ba(d,b,a)},ya:function(a,b){var d=S.dirname(a),e=S.dirname(b),f=S.X(a),g=S.X(b);var k=U.F(a,{parent:!0});var m=k.node;k=U.F(b,{parent:!0});k=k.node;if(!m||!k)throw new U.A(44);if(m.H!==k.H)throw new U.A(75);var r=
U.W(m,f);e=V.zb(a,e);if("."!==e.charAt(0))throw new U.A(28);e=V.zb(b,d);if("."!==e.charAt(0))throw new U.A(55);try{var l=U.W(k,g)}catch(p){}if(r!==l){d=U.K(r.mode);if(f=U.Fa(m,f,d))throw new U.A(f);if(f=l?U.Fa(k,g,d):U.Ya(k,g))throw new U.A(f);if(!m.B.ya)throw new U.A(63);if(U.ea(r)||l&&U.ea(l))throw new U.A(10);if(k!==m&&(f=U.$(m,"w")))throw new U.A(f);try{U.J.willMovePath&&U.J.willMovePath(a,b)}catch(p){y("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+p.message)}U.vb(r);
try{m.B.ya(r,k,g)}catch(p){throw p;}finally{U.ub(r)}try{if(U.J.onMovePath)U.J.onMovePath(a,b)}catch(p){y("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+p.message)}}},za:function(a){var b=U.F(a,{parent:!0}).node,d=S.X(a),e=U.W(b,d),f=U.Fa(b,d,!0);if(f)throw new U.A(f);if(!b.B.za)throw new U.A(63);if(U.ea(e))throw new U.A(10);try{U.J.willDeletePath&&U.J.willDeletePath(a)}catch(g){y("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.B.za(b,
d);U.La(e);try{if(U.J.onDeletePath)U.J.onDeletePath(a)}catch(g){y("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},xa:function(a){a=U.F(a,{O:!0}).node;if(!a.B.xa)throw new U.A(54);return a.B.xa(a)},na:function(a){var b=U.F(a,{parent:!0}).node,d=S.X(a),e=U.W(b,d),f=U.Fa(b,d,!1);if(f)throw new U.A(f);if(!b.B.na)throw new U.A(63);if(U.ea(e))throw new U.A(10);try{U.J.willDeletePath&&U.J.willDeletePath(a)}catch(g){y("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+
g.message)}b.B.na(b,d);U.La(e);try{if(U.J.onDeletePath)U.J.onDeletePath(a)}catch(g){y("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},aa:function(a){a=U.F(a).node;if(!a)throw new U.A(44);if(!a.B.aa)throw new U.A(28);return V.resolve(U.Z(a.parent),a.B.aa(a))},stat:function(a,b){a=U.F(a,{O:!b}).node;if(!a)throw new U.A(44);if(!a.B.R)throw new U.A(63);return a.B.R(a)},ad:function(a){return U.stat(a,!0)},Ba:function(a,b,d){var e;"string"===typeof a?e=U.F(a,{O:!d}).node:
e=a;if(!e.B.L)throw new U.A(63);e.B.L(e,{mode:b&4095|e.mode&-4096,timestamp:Date.now()})},Yc:function(a,b){U.Ba(a,b,!0)},Rc:function(a,b){a=U.ca(a);if(!a)throw new U.A(8);U.Ba(a.node,b)},hb:function(a,b,d,e){var f;"string"===typeof a?f=U.F(a,{O:!e}).node:f=a;if(!f.B.L)throw new U.A(63);f.B.L(f,{timestamp:Date.now()})},Zc:function(a,b,d){U.hb(a,b,d,!0)},Sc:function(a,b,d){a=U.ca(a);if(!a)throw new U.A(8);U.hb(a.node,b,d)},truncate:function(a,b){if(0>b)throw new U.A(28);var d;"string"===typeof a?d=
U.F(a,{O:!0}).node:d=a;if(!d.B.L)throw new U.A(63);if(U.K(d.mode))throw new U.A(31);if(!U.isFile(d.mode))throw new U.A(28);if(a=U.$(d,"w"))throw new U.A(a);d.B.L(d,{size:b,timestamp:Date.now()})},Uc:function(a,b){a=U.ca(a);if(!a)throw new U.A(8);if(0===(a.flags&2097155))throw new U.A(28);U.truncate(a.node,b)},od:function(a,b,d){a=U.F(a,{O:!0}).node;a.B.L(a,{timestamp:Math.max(b,d)})},open:function(a,b,d,e,f){if(""===a)throw new U.A(44);b="string"===typeof b?U.pc(b):b;d=b&64?("undefined"===typeof d?
438:d)&4095|32768:0;if("object"===typeof a)var g=a;else{a=S.normalize(a);try{g=U.F(a,{O:!(b&131072)}).node}catch(m){}}var k=!1;if(b&64)if(g){if(b&128)throw new U.A(20);}else g=U.T(a,d,0),k=!0;if(!g)throw new U.A(44);U.Da(g.mode)&&(b&=-513);if(b&65536&&!U.K(g.mode))throw new U.A(54);if(!k&&(d=U.oc(g,b)))throw new U.A(d);b&512&&U.truncate(g,0);b&=-131713;e=U.Wb({node:g,path:U.Z(g),flags:b,seekable:!0,position:0,D:g.D,Ac:[],error:!1},e,f);e.D.open&&e.D.open(e);!c.logReadFiles||b&1||(U.ab||(U.ab={}),
a in U.ab||(U.ab[a]=1,y("FS.trackingDelegate error on read file: "+a)));try{U.J.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=U.Cb.yb.Hb),0!==(b&2097155)&&(f|=U.Cb.yb.Ib),U.J.onOpenFile(a,f))}catch(m){y("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return e},close:function(a){if(U.ra(a))throw new U.A(8);a.Qa&&(a.Qa=null);try{a.D.close&&a.D.close(a)}catch(b){throw b;}finally{U.Qb(a.ja)}a.ja=null},ra:function(a){return null===a.ja},S:function(a,b,d){if(U.ra(a))throw new U.A(8);
if(!a.seekable||!a.D.S)throw new U.A(70);if(0!=d&&1!=d&&2!=d)throw new U.A(28);a.position=a.D.S(a,b,d);a.Ac=[];return a.position},read:function(a,b,d,e,f){if(0>e||0>f)throw new U.A(28);if(U.ra(a))throw new U.A(8);if(1===(a.flags&2097155))throw new U.A(8);if(U.K(a.node.mode))throw new U.A(31);if(!a.D.read)throw new U.A(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new U.A(70);b=a.D.read(a,b,d,e,f);g||(a.position+=b);return b},write:function(a,b,d,e,f,g){if(0>e||0>f)throw new U.A(28);
if(U.ra(a))throw new U.A(8);if(0===(a.flags&2097155))throw new U.A(8);if(U.K(a.node.mode))throw new U.A(31);if(!a.D.write)throw new U.A(28);a.seekable&&a.flags&1024&&U.S(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new U.A(70);b=a.D.write(a,b,d,e,f,g);k||(a.position+=b);try{if(a.path&&U.J.onWriteToFile)U.J.onWriteToFile(a.path)}catch(m){y("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},qa:function(a,b,d){if(U.ra(a))throw new U.A(8);
if(0>b||0>=d)throw new U.A(28);if(0===(a.flags&2097155))throw new U.A(8);if(!U.isFile(a.node.mode)&&!U.K(a.node.mode))throw new U.A(43);if(!a.D.qa)throw new U.A(138);a.D.qa(a,b,d)},ta:function(a,b,d,e,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new U.A(2);if(1===(a.flags&2097155))throw new U.A(2);if(!a.D.ta)throw new U.A(43);return a.D.ta(a,b,d,e,f,g)},la:function(a,b,d,e,f){return a&&a.D.la?a.D.la(a,b,d,e,f):0},ed:function(){return 0},Ua:function(a,b,d){if(!a.D.Ua)throw new U.A(59);
return a.D.Ua(a,b,d)},jd:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var d,e=U.open(a,b.flags);a=U.stat(a).size;var f=new Uint8Array(a);U.read(e,f,0,a,0);"utf8"===b.encoding?d=F(f,0):"binary"===b.encoding&&(d=f);U.close(e);return d},pd:function(a,b,d){d=d||{};d.flags=d.flags||577;a=U.open(a,d.flags,d.mode);if("string"===typeof b){var e=new Uint8Array(H(b)+1);b=G(b,e,0,e.length);
U.write(a,e,0,b,void 0,d.Ob)}else if(ArrayBuffer.isView(b))U.write(a,b,0,b.byteLength,void 0,d.Ob);else throw Error("Unsupported data type");U.close(a)},Ca:function(){return U.lb},Fc:function(a){a=U.F(a,{O:!0});if(null===a.node)throw new U.A(44);if(!U.K(a.node.mode))throw new U.A(54);var b=U.$(a.node,"x");if(b)throw new U.A(b);U.lb=a.path},Sb:function(){U.N("/tmp");U.N("/home");U.N("/home/web_user")},Rb:function(){U.N("/dev");U.cb(U.ha(1,3),{read:function(){return 0},write:function(b,d,e,f){return f}});
U.Ga("/dev/null",U.ha(1,3));W.register(U.ha(5,0),W.Zb);W.register(U.ha(6,0),W.Yb);U.Ga("/dev/tty",U.ha(5,0));U.Ga("/dev/tty1",U.ha(6,0));var a=Fa();U.Y("/dev","random",a);U.Y("/dev","urandom",a);U.N("/dev/shm");U.N("/dev/shm/tmp")},Ub:function(){U.N("/proc");var a=U.N("/proc/self");U.N("/proc/self/fd");U.H({H:function(){var b=U.createNode(a,"fd",16895,73);b.B={ga:function(d,e){var f=U.ca(+e);if(!f)throw new U.A(8);d={parent:null,H:{xb:"fake"},B:{aa:function(){return f.path}}};return d.parent=d}};
return b}},{},"/proc/self/fd")},Vb:function(){c.stdin?U.Y("/dev","stdin",c.stdin):U.ba("/dev/tty","/dev/stdin");c.stdout?U.Y("/dev","stdout",null,c.stdout):U.ba("/dev/tty","/dev/stdout");c.stderr?U.Y("/dev","stderr",null,c.stderr):U.ba("/dev/tty1","/dev/stderr");U.open("/dev/stdin",0);U.open("/dev/stdout",1);U.open("/dev/stderr",1)},nb:function(){U.A||(U.A=function(a,b){this.node=b;this.yc=function(d){this.P=d};this.yc(a);this.message="FS error"},U.A.prototype=Error(),U.A.prototype.constructor=U.A,
[44].forEach(function(a){U.Oa[a]=new U.A(a);U.Oa[a].stack="<generic error, no stack>"}))},zc:function(){U.nb();U.U=Array(4096);U.H(X,{},"/");U.Sb();U.Rb();U.Ub();U.dc={MEMFS:X}},da:function(a,b,d){U.da.Sa=!0;U.nb();c.stdin=a||c.stdin;c.stdout=b||c.stdout;c.stderr=d||c.stderr;U.Vb()},hd:function(){U.da.Sa=!1;var a=c._fflush;a&&a(0);for(a=0;a<U.streams.length;a++){var b=U.streams[a];b&&U.close(b)}},Pa:function(a,b){var d=0;a&&(d|=365);b&&(d|=146);return d},Tc:function(a,b){a=U.Ja(a,b);return a.Ma?a.object:
null},Ja:function(a,b){try{var d=U.F(a,{O:!b});a=d.path}catch(f){}var e={Ea:!1,Ma:!1,error:0,name:null,path:null,object:null,uc:!1,wc:null,vc:null};try{d=U.F(a,{parent:!0}),e.uc=!0,e.wc=d.path,e.vc=d.node,e.name=S.X(a),d=U.F(a,{O:!b}),e.Ma=!0,e.path=d.path,e.object=d.node,e.name=d.node.name,e.Ea="/"===d.path}catch(f){e.error=f.P}return e},Hc:function(a,b){a="string"===typeof a?a:U.Z(a);for(b=b.split("/").reverse();b.length;){var d=b.pop();if(d){var e=S.fa(a,d);try{U.N(e)}catch(f){}a=e}}return e},
Tb:function(a,b,d,e,f){a=S.fa("string"===typeof a?a:U.Z(a),b);return U.create(a,U.Pa(e,f))},kb:function(a,b,d,e,f,g){a=b?S.fa("string"===typeof a?a:U.Z(a),b):a;e=U.Pa(e,f);f=U.create(a,e);if(d){if("string"===typeof d){a=Array(d.length);b=0;for(var k=d.length;b<k;++b)a[b]=d.charCodeAt(b);d=a}U.Ba(f,e|146);a=U.open(f,577);U.write(a,d,0,d.length,0,g);U.close(a);U.Ba(f,e)}return f},Y:function(a,b,d,e){a=S.fa("string"===typeof a?a:U.Z(a),b);b=U.Pa(!!d,!!e);U.Y.Xa||(U.Y.Xa=64);var f=U.ha(U.Y.Xa++,0);U.cb(f,
{open:function(g){g.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(g,k,m,r){for(var l=0,p=0;p<r;p++){try{var u=d()}catch(z){throw new U.A(29);}if(void 0===u&&0===l)throw new U.A(6);if(null===u||void 0===u)break;l++;k[m+p]=u}l&&(g.node.timestamp=Date.now());return l},write:function(g,k,m,r){for(var l=0;l<r;l++)try{e(k[m+l])}catch(p){throw new U.A(29);}r&&(g.node.timestamp=Date.now());return l}});return U.Ga(a,b,f)},qb:function(a){if(a.Va||a.mc||a.link||a.C)return!0;
if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(v)try{a.C=Ga(v(a.url)),a.G=a.C.length}catch(b){throw new U.A(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Gc:function(a,b,d,e,f){function g(){this.Wa=!1;this.Aa=[]}g.prototype.get=function(l){if(!(l>this.length-1||0>l)){var p=
l%this.jb;return this.tb(l/this.jb|0)[p]}};g.prototype.Eb=function(l){this.tb=l};g.prototype.gb=function(){var l=new XMLHttpRequest;l.open("HEAD",d,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+d+". Status: "+l.status);var p=Number(l.getResponseHeader("Content-length")),u,z=(u=l.getResponseHeader("Accept-Ranges"))&&"bytes"===u;l=(u=l.getResponseHeader("Content-Encoding"))&&"gzip"===u;var A=1048576;z||(A=p);var w=this;w.Eb(function(D){var T=D*A,O=(D+
1)*A-1;O=Math.min(O,p-1);if("undefined"===typeof w.Aa[D]){var eb=w.Aa;if(T>O)throw Error("invalid range ("+T+", "+O+") or no bytes requested!");if(O>p-1)throw Error("only "+p+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",d,!1);p!==A&&B.setRequestHeader("Range","bytes="+T+"-"+O);"undefined"!=typeof Uint8Array&&(B.responseType="arraybuffer");B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===
B.status))throw Error("Couldn't load "+d+". Status: "+B.status);T=void 0!==B.response?new Uint8Array(B.response||[]):Ga(B.responseText||"");eb[D]=T}if("undefined"===typeof w.Aa[D])throw Error("doXHR failed!");return w.Aa[D]});if(l||!p)A=p=1,A=p=this.tb(0).length,x("LazyFiles on gzip forces download of the whole file when length is accessed");this.Kb=p;this.Jb=A;this.Wa=!0};if("undefined"!==typeof XMLHttpRequest){var k=new g;Object.defineProperties(k,{length:{get:function(){this.Wa||this.gb();return this.Kb}},
jb:{get:function(){this.Wa||this.gb();return this.Jb}}});k={Va:!1,C:k}}else k={Va:!1,url:d};var m=U.Tb(a,b,k,e,f);k.C?m.C=k.C:k.url&&(m.C=null,m.url=k.url);Object.defineProperties(m,{G:{get:function(){return this.C.length}}});var r={};Object.keys(m.D).forEach(function(l){var p=m.D[l];r[l]=function(){U.qb(m);return p.apply(null,arguments)}});r.read=function(l,p,u,z,A){U.qb(m);l=l.node.C;if(A>=l.length)return 0;z=Math.min(l.length-A,z);if(l.slice)for(var w=0;w<z;w++)p[u+w]=l[A+w];else for(w=0;w<z;w++)p[u+
w]=l.get(A+w);return z};m.D=r;return m},Ic:function(a,b,d,e,f,g,k,m,r,l){function p(z){function A(D){l&&l();m||U.kb(a,b,D,e,f,r);g&&g();wa()}var w=!1;c.preloadPlugins.forEach(function(D){!w&&D.canHandle(u)&&(D.handle(z,u,A,function(){k&&k();wa()}),w=!0)});w||A(z)}Ja.da();var u=b?V.resolve(S.fa(a,b)):a;va();"string"==typeof d?Ja.Dc(d,function(z){p(z)},k):p(d)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},eb:function(){return"EM_FS_"+
window.location.pathname},fb:20,pa:"FILE_DATA",kd:function(a,b,d){b=b||function(){};d=d||function(){};var e=U.indexedDB();try{var f=e.open(U.eb(),U.fb)}catch(g){return d(g)}f.onupgradeneeded=function(){x("creating db");f.result.createObjectStore(U.pa)};f.onsuccess=function(){var g=f.result.transaction([U.pa],"readwrite"),k=g.objectStore(U.pa),m=0,r=0,l=a.length;a.forEach(function(p){p=k.put(U.Ja(p).object.C,p);p.onsuccess=function(){m++;m+r==l&&(0==r?b():d())};p.onerror=function(){r++;m+r==l&&(0==
r?b():d())}});g.onerror=d};f.onerror=d},$c:function(a,b,d){b=b||function(){};d=d||function(){};var e=U.indexedDB();try{var f=e.open(U.eb(),U.fb)}catch(g){return d(g)}f.onupgradeneeded=d;f.onsuccess=function(){var g=f.result;try{var k=g.transaction([U.pa],"readonly")}catch(u){d(u);return}var m=k.objectStore(U.pa),r=0,l=0,p=a.length;a.forEach(function(u){var z=m.get(u);z.onsuccess=function(){U.Ja(u).Ma&&U.na(u);U.kb(S.dirname(u),S.X(u),z.result,!0,!0,!0);r++;r+l==p&&(0==l?b():d())};z.onerror=function(){l++;
r+l==p&&(0==l?b():d())}});k.onerror=d};f.onerror=d}};c.FS=U;
var Y={bd:{},Bc:5,md:511,Ec:function(a,b,d){if("/"===b[0])return b;if(-100===a)a=U.Ca();else{a=U.ca(a);if(!a)throw new U.A(8);a=a.path}if(0==b.length){if(!d)throw new U.A(44);return a}return S.fa(a,b)},Pc:function(a,b,d){try{var e=a(b)}catch(f){if(f&&f.node&&S.normalize(b)!==S.normalize(U.Z(f.node)))return-54;throw f;}K[d>>2]=e.$b;K[d+4>>2]=0;K[d+8>>2]=e.Ta;K[d+12>>2]=e.mode;K[d+16>>2]=e.tc;K[d+20>>2]=e.uid;K[d+24>>2]=e.jc;K[d+28>>2]=e.wa;K[d+32>>2]=0;Q=[e.size>>>0,(P=e.size,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];K[d+40>>2]=Q[0];K[d+44>>2]=Q[1];K[d+48>>2]=4096;K[d+52>>2]=e.Nb;K[d+56>>2]=e.Lb.getTime()/1E3|0;K[d+60>>2]=0;K[d+64>>2]=e.qc.getTime()/1E3|0;K[d+68>>2]=0;K[d+72>>2]=e.Xb.getTime()/1E3|0;K[d+76>>2]=0;Q=[e.Ta>>>0,(P=e.Ta,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];K[d+80>>2]=Q[0];K[d+84>>2]=Q[1];return 0},Nc:function(a,b,d,e,f){U.la(b,J.slice(a,
a+d),f,d,e)},Lc:function(a,b){a=S.normalize(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));U.N(a,b,0);return 0},Mc:function(a,b,d){switch(b&61440){case 32768:case 8192:case 24576:case 4096:case 49152:break;default:return-28}U.T(a,b,d);return 0},Oc:function(a,b,d){if(0>=d)return-28;a=U.aa(a);var e=Math.min(d,H(a)),f=I[b+e];G(a,J,b,d+1);I[b+e]=f;return e},Jc:function(a,b){if(b&-8)return-28;a=U.F(a,{O:!0}).node;if(!a)return-44;var d="";b&4&&(d+="r");b&2&&(d+="w");b&1&&(d+="x");return d&&U.$(a,d)?
-2:0},Kc:function(a,b,d){var e=U.ca(d);e&&U.close(e);return U.open(a,b,0,d,d).ja},ac:function(a,b,d,e){for(var f=0,g=0;g<d;g++){var k=K[b+(8*g+4)>>2],m=U.read(a,I,K[b+8*g>>2],k,e);if(0>m)return-1;f+=m;if(m<k)break}return f},bc:function(a,b,d,e){for(var f=0,g=0;g<d;g++){var k=U.write(a,I,K[b+8*g>>2],K[b+(8*g+4)>>2],e);if(0>k)return-1;f+=k}return f},oa:void 0,get:function(){Y.oa+=4;return K[Y.oa-4>>2]},ic:function(a){return a?F(J,a,void 0):""},ka:function(a){a=U.ca(a);if(!a)throw new U.A(8);return a},
Vc:function(a){return a}};c.SYSCALLS=Y;function Ka(a,b,d){Y.oa=d;try{var e=Y.ka(a);switch(b){case 0:var f=Y.get();return 0>f?-28:U.open(e.path,e.flags,0,f).ja;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=Y.get(),e.flags|=f,0;case 12:return f=Y.get(),ka[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return Da(28),-1;default:return-28}}catch(g){return"undefined"!==typeof U&&g instanceof U.A||E(g),-g.P}}c.___sys_fcntl64=Ka;
function La(a,b,d){Y.oa=d;try{var e=Y.ka(a);switch(b){case 21509:case 21505:return e.I?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.I?0:-59;case 21519:if(!e.I)return-59;var f=Y.get();return K[f>>2]=0;case 21520:return e.I?-28:-59;case 21531:return f=Y.get(),U.Ua(e,b,f);case 21523:return e.I?0:-59;case 21524:return e.I?0:-59;default:E("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof U&&g instanceof U.A||E(g),-g.P}}c.___sys_ioctl=La;
function Ma(a,b,d){Y.oa=d;try{var e=Y.ic(a),f=d?Y.get():0;return U.open(e,b,f).ja}catch(g){return"undefined"!==typeof U&&g instanceof U.A||E(g),-g.P}}c.___sys_open=Ma;function Na(a,b,d){J.copyWithin(a,b,b+d)}c._emscripten_memcpy_big=Na;function Oa(){return J.length}c._emscripten_get_heap_size=Oa;function Pa(a){try{return da.grow(a-ja.byteLength+65535>>>16),la(),1}catch(b){}}c.emscripten_realloc_buffer=Pa;
function Qa(a){a>>>=0;var b=Oa();if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);if(Pa(Math.min(2147483648,e)))return!0}return!1}c._emscripten_resize_heap=Qa;function Ra(a){Sa(a)}c._exit=Ra;function Ta(a){try{var b=Y.ka(a);U.close(b);return 0}catch(d){return"undefined"!==typeof U&&d instanceof U.A||E(d),d.P}}c._fd_close=Ta;
function Ua(a,b,d,e){try{var f=Y.ka(a),g=Y.ac(f,b,d);K[e>>2]=g;return 0}catch(k){return"undefined"!==typeof U&&k instanceof U.A||E(k),k.P}}c._fd_read=Ua;
function Va(a,b,d,e,f){try{var g=Y.ka(a);a=4294967296*d+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;U.S(g,a,e);Q=[g.position>>>0,(P=g.position,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];K[f>>2]=Q[0];K[f+4>>2]=Q[1];g.Qa&&0===a&&0===e&&(g.Qa=null);return 0}catch(k){return"undefined"!==typeof U&&k instanceof U.A||E(k),k.P}}c._fd_seek=Va;
function Wa(a,b,d,e){try{var f=Y.ka(a),g=Y.bc(f,b,d);K[e>>2]=g;return 0}catch(k){return"undefined"!==typeof U&&k instanceof U.A||E(k),k.P}}c._fd_write=Wa;function Xa(a){var b=Date.now();K[a>>2]=b/1E3|0;K[a+4>>2]=b%1E3*1E3|0;return 0}c._gettimeofday=Xa;function Ya(){}c._setTempRet0=Ya;function Za(a,b,d,e){a||(a=this);this.parent=a;this.H=a.H;this.ua=null;this.id=U.rc++;this.name=b;this.mode=d;this.B={};this.D={};this.wa=e}
Object.defineProperties(Za.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},mc:{get:function(){return U.K(this.mode)}},Va:{get:function(){return U.Da(this.mode)}}});U.Fb=Za;U.zc();var Ja;function Ga(a){var b=Array(H(a)+1);a=G(a,b,0,b.length);b.length=a;return b}var $a={b:Ka,g:La,h:Ma,d:Na,a:Qa,k:Ra,c:Ta,f:Ua,i:Va,e:Wa,l:Xa,j:Ya};
(function(){function a(f){c.asm=f.exports;da=c.asm.m;la();ma=c.asm.v;wa()}function b(f){a(f.instance)}function d(f){return Aa().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){y("failed to asynchronously prepare wasm: "+g);E(g)})}var e={a:$a};va();if(c.instantiateWasm)try{return c.instantiateWasm(e,a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return C||"function"!==typeof WebAssembly.instantiateStreaming||xa()||"function"!==
typeof fetch?d(b):fetch(N,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){y("wasm streaming compile failed: "+g);y("falling back to ArrayBuffer instantiation");return d(b)})})})();return{}})();var sa=c.___wasm_call_ctors=function(){return(sa=c.___wasm_call_ctors=c.asm.n).apply(null,arguments)};c._main=function(){return(c._main=c.asm.o).apply(null,arguments)};
var Ia=c._malloc=function(){return(Ia=c._malloc=c.asm.p).apply(null,arguments)},ab=c._free=function(){return(ab=c._free=c.asm.q).apply(null,arguments)},Ea=c.___errno_location=function(){return(Ea=c.___errno_location=c.asm.r).apply(null,arguments)};c.stackSave=function(){return(c.stackSave=c.asm.s).apply(null,arguments)};c.stackRestore=function(){return(c.stackRestore=c.asm.t).apply(null,arguments)};var ia=c.stackAlloc=function(){return(ia=c.stackAlloc=c.asm.u).apply(null,arguments)};
c.dynCall_jiji=function(){return(c.dynCall_jiji=c.asm.w).apply(null,arguments)};c.callMain=bb;c.FS=U;var Z;function cb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}M=function db(){Z||fb();Z||(M=db)};
function bb(a){var b=c._main;a=a||[];var d=a.length+1,e=ia(4*(d+1));K[e>>2]=ha(ba);for(var f=1;f<d;f++)K[(e>>2)+f]=ha(a[f-1]);K[(e>>2)+d]=0;try{var g=b(d,e);Sa(g,!0)}catch(k){k instanceof cb||("unwind"==k?noExitRuntime=!0:((a=k)&&"object"===typeof k&&k.stack&&(a=[k,k.stack]),y("exception thrown: "+a),q(1,k)))}finally{}}
function fb(a){function b(){if(!Z&&(Z=!0,c.calledRun=!0,!ea)){ra=!0;c.noFSInit||U.da.Sa||U.da();W.da();R(oa);U.wb=!1;R(pa);if(c.onRuntimeInitialized)c.onRuntimeInitialized();gb&&bb(a);if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var d=c.postRun.shift();qa.unshift(d)}R(qa)}}a=a||aa;if(!(0<L)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)ta();R(na);0<L||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);b()},1)):b())}}c.run=fb;function Sa(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(c.onExit)c.onExit(a);ea=!0}q(a,new cb(a))}}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var gb=!0;c.noInitialRun&&(gb=!1);noExitRuntime=!0;fb();
(function(){function a(){if(d&&ra){var g=d;d=null;g.forEach(function(k){onmessage(k)})}}function b(){a();d&&setTimeout(b,100)}var d=null,e=0,f=0;onmessage=function(g){if(ra){a();var k=c["_"+g.data.funcName];if(!k)throw"invalid worker function to call: "+g.data.funcName;if(g=g.data.data){g.byteLength||(g=new Uint8Array(g));if(!e||f<g.length)e&&ab(e),f=g.length,e=Ia(g.length);J.set(g,e)}g?k(e,g.length):k(0,0)}else d||(d=[],setTimeout(b,100)),d.push(g)}})();
